# Generated by Django 4.0.3 on 2022-04-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('mesto', models.CharField(max_length=100, verbose_name='Место работы')),
                ('doljonosti', models.CharField(choices=[('Д', 'Директор'), ('Т', 'Топ-Менеджер'), ('А', 'Администратор'), ('К', 'Консультант'), ('П', 'Продавец')], max_length=1, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
    ]
