# Generated by Django 4.0.4 on 2022-05-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=100, verbose_name='ФИО клиента')),
                ('name_droduct', models.CharField(max_length=50, verbose_name='Название')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона пользователя')),
                ('mail', models.CharField(max_length=50, verbose_name='Почта пользователя')),
                ('addres', models.TextField(verbose_name='Место проживание')),
                ('index_code', models.CharField(max_length=10, verbose_name='Почтовый индекс')),
                ('cost', models.CharField(max_length=50, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
