# Generated by Django 4.0.2 on 2022-03-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50, verbose_name='Почта пользователя')),
            ],
            options={
                'verbose_name': 'Mail',
                'verbose_name_plural': 'Gmail',
            },
        ),
    ]
