# Generated by Django 4.0.4 on 2022-04-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'Почта пользователя', 'verbose_name_plural': 'Почты пользователей'},
        ),
    ]
