# Generated by Django 4.0.2 on 2022-03-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('img', models.ImageField(upload_to='computer', verbose_name='Фотография компьютера')),
                ('title', models.CharField(max_length=250, verbose_name='Описание')),
                ('CPU', models.CharField(max_length=350, verbose_name='Процессор')),
                ('Cooling', models.CharField(max_length=350, verbose_name='Система охлаждения')),
                ('Motherboard', models.CharField(max_length=350, verbose_name='Материнская плата')),
                ('RAM', models.CharField(max_length=350, verbose_name='Оперативная память')),
                ('GPU', models.CharField(max_length=350, verbose_name='Видеокарта')),
                ('SSD', models.CharField(max_length=350, verbose_name='SSD')),
                ('HDD', models.CharField(max_length=350, verbose_name='Жесткий диск')),
                ('Power', models.CharField(max_length=350, verbose_name='Блок питания')),
                ('Box', models.CharField(max_length=350, verbose_name='Корпус')),
                ('Windows', models.CharField(max_length=350, verbose_name='Windows')),
                ('Cost', models.CharField(max_length=50, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
        migrations.CreateModel(
            name='Periferia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('img', models.ImageField(upload_to='periferia', verbose_name='Фотография переферии')),
                ('title', models.CharField(max_length=250, verbose_name='Описание')),
                ('Cost', models.CharField(max_length=50, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Периферия',
                'verbose_name_plural': 'Периферия',
            },
        ),
    ]
